graphite:
  ports:
    - "8082:80"
    - "2003:2003"
    - "2004:2004"
    - "7002:7002"
  image: jstenhouse/graphite:latest


ganglia:
  ports:
    - "8083:80"
    - "8649:8649"
    - "8649:8649/udp"
  image: mbocek/ganglia:latest


grafana:
  ports:
    - "8084:3000"
  image: grafana/grafana:latest


bitcoin_address_service:
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - graphite
    - ganglia
  image: jstenhouse/bitcoin_address_service:latest
