# graphite:
#   ports:
#     - "8082:80"
#     - "2003:2003"
#     - "2004:2004"
#     - "7002:7002"
#   image: jstenhouse/graphite:latest


graphite:
  ports:
    - "8082:80"
    - "2003:2003"
    - "8125:8125/udp"
    - "8126:8126"
  image: hopsoft/graphite-statsd:latest


elk:
  ports:
    - "9292:9292"
    - "9200:9200"
    - "5000:5000"
    - "5000:5000/udp"
  environment:
    LOGSPOUT: ignore
  volumes:
    - config:/opt/logstash/conf.d
  image: pblittle/docker-logstash:latest


logspout:
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: syslog://localhost:5000
  image: gliderlabs/logspout:latest


ganglia:
  ports:
    - "8083:80"
    - "8649:8649"
    - "8649:8649/udp"
  image: mbocek/ganglia:latest


grafana:
  ports:
    - "8084:3000"
  image: grafana/grafana:latest


bitcoin_address_service:
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - graphite
    - ganglia
  image: jstenhouse/bitcoin_address_service:latest
