discovery_ping:
  ports:
    - "8080:8080"
  environment:
    SERVER_PORT: 8080
  image: jstenhouse/discovery_example:latest

discovery_pong:
  ports:
    - "8081:8081"
  environment:
    SERVER_PORT: 8081
  image: jstenhouse/discovery_example:latest

disovery_discovery:
  ports:
    - "8082:8082"
  environment:
    SERVER_PORT: 8082
  image: jstenhouse/discovery_example:latest
