discovery_ping:
  ports:
    - "8080:8080"
  environment:
    SERVICE_NAME: ping
    SERVER_PORT: 8080
  links:
    - etcd
  image: jstenhouse/discovery_example:latest

discovery_pong:
  ports:
    - "8081:8081"
  environment:
    SERVICE_NAME: pong
    SERVER_PORT: 8081
  links:
    - etcd
  image: jstenhouse/discovery_example:latest

disovery_discovery:
  ports:
    - "8082:8082"
  environment:
    SERVICE_NAME: discovery
    SERVER_PORT: 8082
  links:
    - etcd
  image: jstenhouse/discovery_example:latest

etcd:
  ports:
    - "2379:2379"
    - "2380:2380"
    - "4001:4001"
  command: -name etcd -advertise-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001 -initial-cluster-token etcd-cluster -initial-cluster-state new
  image: quay.io/coreos/etcd:v2.2.3
